In [1]:
import requests
import numpy as np
import pandas as pd
from itertools import product
import matplotlib.pyplot as plt

In [2]:
code_to_state = {33: 'RJ', 32: 'ES', 41: 'PR', 23: 'CE', 21: 'MA',
 31: 'MG', 42: 'SC', 26: 'PE', 25: 'PB', 24: 'RN', 22: 'PI', 27: 'AL',
 28: 'SE', 35: 'SP', 43: 'RS', 15: 'PA', 16: 'AP', 14: 'RR',  11: 'RO',
 13: 'AM', 12: 'AC', 51: 'MT', 50: 'MS', 52: 'GO', 17: 'TO', 53: 'DF',
 29: 'BA'}

code_to_state.values()

dict_values(['RJ', 'ES', 'PR', 'CE', 'MA', 'MG', 'SC', 'PE', 'PB', 'RN', 'PI', 'AL', 'SE', 'SP', 'RS', 'PA', 'AP', 'RR', 'RO', 'AM', 'AC', 'MT', 'MS', 'GO', 'TO', 'DF', 'BA'])

In [3]:
%%time
episcanner_api = "https://api.mosqlimate.org/api/datastore/episcanner/"

for state in code_to_state.values():
    df = pd.DataFrame()

    for year in  np.arange(2011, 2025):
        params = {
            "disease": "dengue",
            "uf": f"{state}",
            "year": f"{year}",
        }

        try:
            resp = requests.get(episcanner_api, params=params)
            
            items = resp.json()
            df_ = pd.DataFrame(items)
        except:
            print(state)
            print(year)

        df = pd.concat([df, df_])

    df.to_csv(f'episcanner_{state}.csv.gz')

ES
2021
SC
2012
RS
2018
AP
2020
CPU times: user 6.23 s, sys: 594 ms, total: 6.82 s
Wall time: 8min 5s

In [6]:
df = pd.read_csv('episcanner_PR.csv.gz', index_col = 'Unnamed: 0')

df.head()

,disease,CID10,year,geocode,muni_name,peak_week,beta,gamma,R0,total_cases,alpha,sum_res,ep_ini,ep_end,ep_dur
0,dengue,A90,2011,4121307,Rancho Alegre,17.665344,0.530386,0.302060,1.755899,122.139904,0.430491,1.719328,201046,201123,29
1,dengue,A90,2011,4103701,Cambé,18.475896,0.487888,0.300000,1.626295,2643.397200,0.385105,1.560954,201046,201126,32
2,dengue,A90,2011,4111902,Jaguapitã,19.346801,0.455436,0.300700,1.514588,654.607611,0.339754,1.974255,201046,201129,35
3,dengue,A90,2011,4102406,Bandeirantes,21.009654,0.571329,0.301734,1.893486,468.871287,0.471874,0.634372,201051,201125,26
4,dengue,A90,2011,4109203,Guaraci,18.068354,0.430141,0.300000,1.433802,149.282499,0.302554,2.281382,201046,201130,36